[tool.poetry]
name = "lcd-font-samples"
version = "0.1.0"
description = ""
authors = ["osatou0141 <gbtikin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
a = "^1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
